sonar.projectKey=simple-object-storage
sonar.projectName=SOS - Simple Object Storage

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=build/classes/java/main

sonar.exclusions=**/build/**,**/generated/**
sonar.coverage.exclusions=**/generated/**
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.qualitygate.wait=true
